# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo List' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  pod 'IQKeyboardManager'

  # Pods for Todo List

  target 'Todo ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Todo ListUITests' do
    # Pods for testing
  end

end
